---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-autoscaling-phihos-github-io-v1alpha1-cranepodautoscaler
    failurePolicy: Fail
    name: mcranepodautoscaler.kb.io
    rules:
      - apiGroups:
          - autoscaling.phihos.github.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cranepodautoscalers
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-autoscaling-phihos-github-io-v1alpha1-cranepodautoscaler
    failurePolicy: Fail
    name: vcranepodautoscaler.kb.io
    rules:
      - apiGroups:
          - autoscaling.phihos.github.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cranepodautoscalers
    sideEffects: None
