---
# permissions for end users to edit cranepodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tmp
    app.kubernetes.io/managed-by: kustomize
  name: cranepodautoscaler-editor-role
rules:
  - apiGroups:
      - autoscaling.phihos.github.io
    resources:
      - cranepodautoscalers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - autoscaling.phihos.github.io
    resources:
      - cranepodautoscalers/status
    verbs:
      - get
