---
resources:
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  # RBAC for protecting the metrics endpoint with authn/authz.
  - metrics_auth_role.yaml
  - metrics_auth_role_binding.yaml
  - metrics_reader_role.yaml
  # Convenience roles for end users.
  - cranepodautoscaler_editor_role.yaml
  - cranepodautoscaler_viewer_role.yaml
