---
resources:
  - bases/autoscaling.phihos.github.io_cranepodautoscalers.yaml
patches:
  # Enable the conversion webhook for the CRD
  - path: patches/webhook_in_cranepodautoscalers.yaml

# Uncomment to teach kustomize how to do kustomization for CRDs with webhooks
# configurations:
#   - kustomizeconfig.yaml
