name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github. run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          determinate: true

      - name: Set up magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Set up Go cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-go-

      - name: Prepare Nix shell
        run: nix develop --impure .#ci

      - name: Lint
        run: nix develop --impure .#ci -c make lint -j

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          determinate: true

      - name: Set up magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Set up Go cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-go-

      - name: Prepare Nix shell
        run: nix develop --impure .#ci

      - name: Test
        run: nix develop --impure .#ci -c make test

  acceptance-test:
    name: Acceptance test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: ["v1.28.9", "v1.29.4", "v1.30.8", "v1.31.4", "v1.32.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          determinate: true

      - name: Set up magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Prepare Nix shell
        run: nix develop --impure .#ci

      - name: Start kind cluster
        run: kind create cluster --image kindest/node:${{ matrix.k8s_version }} --wait 1m

      - name: Acceptance test
        run: nix develop --impure .#ci -c make test-e2e
